interface StateInfo {
    image : string;
}

const stateInfo : Record<string, StateInfo> = {
    "alabama" : {image: '/States/alabama.svg'},
    "alaska" : {image: '/States/alaska.svg'},
    "arizona" : {image: '/States/arizona.svg'},
    "arkansas" : {image: '/States/arkansas.svg'},
    "california" : {image: '/States/california.svg'},
    "colorado" : {image: '/States/colorado.svg'},
    "connecticut" : {image: '/States/connecticut.svg'},
    "delaware" : {image: '/States/delaware.svg'},
    "florida" : {image: '/States/florida.svg'},
    "georgia" : {image: '/States/georgia.svg'},
    "hawaii" : {image: '/States/hawaii.svg'},
    "idaho" : {image: '/States/idaho.svg'},
    "illinois" : {image: '/States/illinois.svg'},
    "indiana" : {image: '/States/indiana.svg'},
    "iowa" : {image: '/States/iowa.svg'},
    "kansas" : {image: '/States/kansas.svg'},
    "kentucky" : {image: '/States/kentucky.svg'},
    "louisiana" : {image: '/States/louisiana.svg'},
    "maine" : {image: '/States/maine.svg'},
    "maryland" : {image: '/States/maryland.svg'},
    "massachusetts" : {image: '/States/massachusetts.svg'},
    "michigan" : {image: '/States/michigan.svg'},
    "minnesota" : {image: '/States/minnesota.svg'},
    "mississippi" : {image: '/States/mississippi.svg'},
    "missouri" : {image: '/States/missouri.svg'},
    "montana" : {image: '/States/montana.svg'},
    "nebraska" : {image: '/States/nebraska.svg'},
    "nevada" : {image: '/States/nevada.svg'},
    "new_hampshire" : {image: '/States/new_hampshire.svg'},
    "new_jersey" : {image: '/States/new_jersey.svg'},
    "new_mexico" : {image: '/States/new_mexico.svg'},
    "new_york" : {image: '/States/new_york.svg'},
    "north_carolina" : {image: '/States/north_carolina.svg'},
    "north_dakota" : {image: '/States/north_dakota.svg'},
    "ohio" : {image: '/States/ohio.svg'},
    "oklahoma" : {image: '/States/oklahoma.svg'},
    "oregon" : {image: '/States/oregon.svg'},
    "pennsylvania" : {image: '/States/pennsylvania.svg'},
    "rhode_island" : {image: '/States/rhode_island.svg'},
    "south_carolina" : {image: '/States/south_carolina.svg'},
    "south_dakota" : {image: '/States/south_dakota.svg'},
    "tennessee" : {image: '/States/tennessee.svg'},
    "texas" : {image: '/States/texas.svg'},
    "utah" : {image: '/States/alabama.svg'},
    "vermont" : {image: '/States/vermont.svg'},
    "virginia" : {image: '/States/virginia.svg'},
    "washington" : {image: '/States/washington.svg'},
    "west_virginia" : {image: '/States/west_virginia.svg'},
    "wisconsin" : {image: '/States/wisconsin.svg'},
    "wyoming" : {image: '/States/wyoming.svg'},
};

export default stateInfo;