interface StateInfo {
    image : string;
    eVRebate : number;
    hybridRebate : number;
}

const stateInfo : Record<string, StateInfo> = {
    "alabama" : {image: '/States/alabama.svg', eVRebate : 0, hybridRebate: 0},
    "alaska" : {image: '/States/alaska.svg', eVRebate : 1000, hybridRebate : 0},
    "arizona" : {image: '/States/arizona.svg', eVRebate : 0, hybridRebate: 0},
    "arkansas" : {image: '/States/arkansas.svg', eVRebate : 0, hybridRebate: 0},
    "california" : {image: '/States/california.svg', eVRebate : 7500, hybridRebate : 0},
    "colorado" : {image: '/States/colorado.svg', eVRebate : 5000, hybridRebate : 5000},
    "connecticut" : {image: '/States/connecticut.svg', eVRebate : 7500, hybridRebate : 7500},
    "delaware" : {image: '/States/delaware.svg', eVRebate : 2500, hybridRebate : 1500},
    "florida" : {image: '/States/florida.svg', eVRebate : 0, hybridRebate: 0},
    "georgia" : {image: '/States/georgia.svg', eVRebate : 0, hybridRebate: 0},
    "hawaii" : {image: '/States/hawaii.svg', eVRebate : 0, hybridRebate: 0},
    "idaho" : {image: '/States/idaho.svg', eVRebate : 0, hybridRebate: 0},
    "illinois" : {image: '/States/illinois.svg', eVRebate : 4000, hybridRebate: 0},
    "indiana" : {image: '/States/indiana.svg', eVRebate : 0, hybridRebate: 0},
    "iowa" : {image: '/States/iowa.svg', eVRebate : 0, hybridRebate: 0},
    "kansas" : {image: '/States/kansas.svg', eVRebate : 2400, hybridRebate: 0},
    "kentucky" : {image: '/States/kentucky.svg', eVRebate : 0, hybridRebate: 0},
    "louisiana" : {image: '/States/louisiana.svg', eVRebate : 0, hybridRebate: 0},
    "maine" : {image: '/States/maine.svg', eVRebate : 7500, hybridRebate: 0},
    "maryland" : {image: '/States/maryland.svg', eVRebate : 3000, hybridRebate: 0},
    "massachusetts" : {image: '/States/massachusetts.svg', eVRebate : 6000, hybridRebate: 0},
    "michigan" : {image: '/States/michigan.svg', eVRebate : 0, hybridRebate: 0},
    "minnesota" : {image: '/States/minnesota.svg', eVRebate : 0, hybridRebate: 0},
    "mississippi" : {image: '/States/mississippi.svg', eVRebate : 0, hybridRebate: 0},
    "missouri" : {image: '/States/missouri.svg', eVRebate : 0, hybridRebate: 0},
    "montana" : {image: '/States/montana.svg', eVRebate : 0, hybridRebate: 0},
    "nebraska" : {image: '/States/nebraska.svg', eVRebate : 0, hybridRebate: 0},
    "nevada" : {image: '/States/nevada.svg', eVRebate : 0, hybridRebate: 0},
    "new_hampshire" : {image: '/States/new_hampshire.svg', eVRebate : 0, hybridRebate: 0},
    "new_jersey" : {image: '/States/new_jersey.svg', eVRebate : 4000, hybridRebate: 0},
    "new_mexico" : {image: '/States/new_mexico.svg', eVRebate : 0, hybridRebate: 0},
    "new_york" : {image: '/States/new_york.svg', eVRebate : 2000, hybridRebate: 0},
    "north_carolina" : {image: '/States/north_carolina.svg', eVRebate : 0, hybridRebate: 0},
    "north_dakota" : {image: '/States/north_dakota.svg', eVRebate : 0, hybridRebate: 0},
    "ohio" : {image: '/States/ohio.svg', eVRebate : 0, hybridRebate: 0},
    "oklahoma" : {image: '/States/oklahoma.svg', eVRebate :5500, hybridRebate: 0},
    "oregon" : {image: '/States/oregon.svg', eVRebate : 5000, hybridRebate: 0},
    "pennsylvania" : {image: '/States/pennsylvania.svg', eVRebate : 3000, hybridRebate: 0},
    "rhode_island" : {image: '/States/rhode_island.svg', eVRebate : 2500, hybridRebate: 0},
    "south_carolina" : {image: '/States/south_carolina.svg', eVRebate : 0, hybridRebate: 0},
    "south_dakota" : {image: '/States/south_dakota.svg', eVRebate : 0, hybridRebate: 0},
    "tennessee" : {image: '/States/tennessee.svg', eVRebate : 0, hybridRebate: 0},
    "texas" : {image: '/States/texas.svg', eVRebate : 0, hybridRebate: 0},
    "utah" : {image: '/States/utah.svg', eVRebate : 0, hybridRebate: 0},
    "vermont" : {image: '/States/vermont.svg', eVRebate : 4000, hybridRebate: 0},
    "virginia" : {image: '/States/virginia.svg', eVRebate : 2500, hybridRebate: 0},
    "washington" : {image: '/States/washington.svg', eVRebate : 0, hybridRebate: 0},
    "west_virginia" : {image: '/States/west_virginia.svg', eVRebate : 0, hybridRebate: 0},
    "wisconsin" : {image: '/States/wisconsin.svg', eVRebate : 0, hybridRebate: 0},
    "wyoming" : {image: '/States/wyoming.svg', eVRebate : 0, hybridRebate: 0},
};

export default stateInfo;