interface StateInfo {
    image: string;
    eVRebate: number;
    hybridRebate: number;
    salesTaxExemption: boolean;
    propertyTaxExemption: boolean;
    homeValueIncrease: boolean;
    solarCredit: string;
    netMetering: boolean;
    naturalGasPrice2022: number;
    electricityPrice2024: number;
}

const stateInfo: Record<string, StateInfo> = {
    "alabama": {
        image: '/States/alabama.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 13.52,
        electricityPrice2024 :12.41
    },
    "alaska": {
        image: '/States/alaska.svg',
        eVRebate: 1000,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 10.13,
        electricityPrice2024 : 22.54
    },
    "arizona": {
        image: '/States/arizona.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: true,
        propertyTaxExemption: true,
        homeValueIncrease: true,
        solarCredit: "up to $1000 or 25% of purchase price",
        netMetering: true,
        naturalGasPrice2022 : 10.81,
        electricityPrice2024 : 13.61
    },
    "arkansas": {
        image: '/States/arkansas.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: true,
        solarCredit: "",
        netMetering: true,
        naturalGasPrice2022 : 12.80,
        electricityPrice2024 : 9.99
    },
    "california": {
        image: '/States/california.svg',
        eVRebate: 7500,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: true,
        homeValueIncrease: false,
        solarCredit: "the SGIP and DAC-SASH program offers rebates and credits for people of all incomes",
        netMetering: true,
        naturalGasPrice2022 : 16.13,
        electricityPrice2024 : 19.90
    },
    "colorado": {
        image: '/States/colorado.svg',
        eVRebate: 5000,
        hybridRebate: 5000,
        salesTaxExemption: false,
        propertyTaxExemption: true,
        homeValueIncrease: false,
        solarCredit: "there are possible solar tax rebates from your power company",
        netMetering: true,
        naturalGasPrice2022 : 11.38,
        electricityPrice2024 : 12.28
    },
    "connecticut": {
        image: '/States/connecticut.svg',
        eVRebate: 7500,
        hybridRebate: 7500,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 12.85,
        electricityPrice2024 : 21.62
    },
    "delaware": {
        image: '/States/delaware.svg',
        eVRebate: 2500,
        hybridRebate: 1500,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 12.37,
        electricityPrice2024 : 12.05
    },
    "florida": {
        image: '/States/florida.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: true,
        propertyTaxExemption: true,
        homeValueIncrease: false,
        solarCredit: "there are tax credits from $2,000 to $4,000 depending on where you live",
        netMetering: true,
        naturalGasPrice2022 : 14.18,
        electricityPrice2024 : 11.37
    },
    "georgia": {
        image: '/States/georgia.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: true,
        naturalGasPrice2022 : 11.39,
        electricityPrice2024 : 12.26
    },
    "hawaii": {
        image: '/States/hawaii.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 44.12,
        electricityPrice2024 : 32.76
    },
    "idaho": {
        image: '/States/idaho.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 7.10,
        electricityPrice2024 : 10.58
    },
    "illinois": {
        image: '/States/illinois.svg',
        eVRebate: 4000,
        hybridRebate: 0, salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: true,
        naturalGasPrice2022 : 12.20,
        electricityPrice2024 : 12.56
    },
    "indiana": {
        image: '/States/indiana.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 9.50,
        electricityPrice2024 : 12.02
    },
    "iowa": {
        image: '/States/iowa.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: true,
        propertyTaxExemption: true,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: true,
        naturalGasPrice2022 : 11.09,
        electricityPrice2024 : 13.81
    },
    "kansas": {
        image: '/States/kansas.svg',
        eVRebate: 2400,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: true,
        homeValueIncrease: true,
        solarCredit: "",
        netMetering: true,
        naturalGasPrice2022 : 12.33,
        electricityPrice2024 : 11.56
    },
    "kentucky": {
        image: '/States/kentucky.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 12.17,
        electricityPrice2024 : 10.56
    },
    "louisiana": {
        image: '/States/louisiana.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: true,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 13.02,
        electricityPrice2024 : 9.37
    },
    "maine": {
        image: '/States/maine.svg',
        eVRebate: 7500,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 16.57,
        electricityPrice2024 : 16.16
    },
    "maryland": {
        image: '/States/maryland.svg',
        eVRebate: 3000,
        hybridRebate: 0,
        salesTaxExemption: true,
        propertyTaxExemption: true,
        homeValueIncrease: false,
        solarCredit: "$1000 for a solar rebate, 30% or up to $5000 for a backup battery, certificate programs, and a clean energy grant for $1000",
        netMetering: true,
        naturalGasPrice2022 : 14.12,
        electricityPrice2024 : 13.92
    },
    "massachusetts": {
        image: '/States/massachusetts.svg',
        eVRebate: 6000,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 15.56,
        electricityPrice2024 : 21.11
    },
    "michigan": {
        image: '/States/michigan.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 10.00,
        electricityPrice2024 : 16.07
    },
    "minnesota": {
        image: '/States/minnesota.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 10.59,
        electricityPrice2024 : 14.09
    },
    "mississippi": {
        image: '/States/mississippi.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: true,
        naturalGasPrice2022 : 12.20,
        electricityPrice2024 : 11.55
    },
    "missouri": {
        image: '/States/missouri.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 11.25,
        electricityPrice2024 :13.23
    },
    "montana": {
        image: '/States/montana.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 10.22,
        electricityPrice2024 : 11.85
    },
    "nebraska": {
        image: '/States/nebraska.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: true,
        naturalGasPrice2022 : 10.31,
        electricityPrice2024 : 11.31
    },
    "nevada": {
        image: '/States/nevada.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: true,
        naturalGasPrice2022 : 9.39,
        electricityPrice2024 : 11.67
    },
    "new_hampshire": {
        image: '/States/new_hampshire.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 16.24,
        electricityPrice2024 : 19.63
    },
    "new_jersey": {
        image: '/States/new_jersey.svg',
        eVRebate: 4000,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 13.08,
        electricityPrice2024 : 15.64
    },
    "new_mexico": {
        image: '/States/new_mexico.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "10% of cost up to $6000",
        netMetering: false,
        naturalGasPrice2022 : 10.34,
        electricityPrice2024 : 13.37
    },
    "new_york": {
        image: '/States/new_york.svg',
        eVRebate: 2000,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 10.31,
        electricityPrice2024 : 19.30
    },
    "north_carolina": {
        image: '/States/north_carolina.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: true,
        homeValueIncrease: false,
        solarCredit: "up to $6000 from generating electricity and low interest loans available",
        netMetering: true,
        naturalGasPrice2022 : 12.35,
        electricityPrice2024 : 11.24
    },
    "north_dakota": {
        image: '/States/north_dakota.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 9.62,
        electricityPrice2024 : 12.07
    },
    "ohio": {
        image: '/States/ohio.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 8.39,
        electricityPrice2024 : 12.64
    },
    "oklahoma": {
        image: '/States/oklahoma.svg',
        eVRebate: 5500,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: true,
        naturalGasPrice2022 : 11.66,
        electricityPrice2024 : 10.72
    },
    "oregon": {
        image: '/States/oregon.svg',
        eVRebate: 5000,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 10.33,
        electricityPrice2024 : 11.02
    },
    "pennsylvania": {
        image: '/States/pennsylvania.svg',
        eVRebate: 3000,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 12.27,
        electricityPrice2024 :14.38
    },
    "rhode_island": {
        image: '/States/rhode_island.svg',
        eVRebate: 2500,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 15.29,
        electricityPrice2024 : 18.64
    },
    "south_carolina": {
        image: '/States/south_carolina.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: true,
        homeValueIncrease: false,
        solarCredit: "there is a 25% state tax credit along with additional rebates for specific power companies",
        netMetering: true,
        naturalGasPrice2022 : 12.15,
        electricityPrice2024 :12.91
    },
    "south_dakota": {
        image: '/States/south_dakota.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 9.25,
        electricityPrice2024 :12.39
    },
    "tennessee": {
        image: '/States/tennessee.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: true,
        propertyTaxExemption: false,
        homeValueIncrease: true,
        solarCredit: "$20 of value added to your home for every $1 saved",
        netMetering: false,
        naturalGasPrice2022 : 11.53,
        electricityPrice2024 :10.79
    },
    "texas": {
        image: '/States/texas.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: true,
        homeValueIncrease: false,
        solarCredit: "there are local rebates, check out your local government's website",
        netMetering: true,
        naturalGasPrice2022 : 11.56,
        electricityPrice2024 :11.36
    },
    "utah": {
        image: '/States/utah.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 8.92,
        electricityPrice2024 :10.63
    },
    "vermont": {
        image: '/States/vermont.svg',
        eVRebate: 4000,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 8.73,
        electricityPrice2024 :18.50
    },
    "virginia": {
        image: '/States/virginia.svg',
        eVRebate: 2500,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: true,
        homeValueIncrease: false,
        solarCredit: "certificate programs",
        netMetering: true,
        naturalGasPrice2022 : 11.54,
        electricityPrice2024 :12.40
    },
    "washington": {
        image: '/States/washington.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 10.63,
        electricityPrice2024 :9.79
    },
    "west_virginia": {
        image: '/States/west_virginia.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 9.69,
        electricityPrice2024 : 11.57
    },
    "wisconsin": {
        image: '/States/wisconsin.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 9.55,
        electricityPrice2024 :14.28
    },
    "wyoming": {
        image: '/States/wyoming.svg',
        eVRebate: 0,
        hybridRebate: 0,
        salesTaxExemption: false,
        propertyTaxExemption: false,
        homeValueIncrease: false,
        solarCredit: "",
        netMetering: false,
        naturalGasPrice2022 : 11.07,
        electricityPrice2024 :12.30
    },
};

const statesArray = [
    'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia',
    'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts',
    'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey',
    'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island',
    'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia',
    'Wisconsin', 'Wyoming'
];
export {stateInfo, statesArray};


